# https://jekyllrb-ko.github.io/docs 가이드 참고

title: 권영광 | Android Engineer
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: 권영광
  bio: Android Engineer
  email: kwon0koang@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# 컬렉션을 시퀀스로 정의할 때, 포함된 페이지들이 자동으로 렌더링되지 않습니다. 
# 이를 활성화하려면, 컬렉션에 output: true 가 지정되어 있어야 하는데, 이는 컬렉션을 매핑으로 정의하는 것과 같습니다. 더 자세한 내용은, 출력 섹션을 참고하세요.
# 컬렉션을 한 곳에 모으세요3.7.0
# 선택사항으로서, 당신의 모든 컬렉션을 한 곳에 보관하기 위해 collections_dir: my_collections 로 디렉토리를 지정할 수 있습니다.
# 그럼 Jekyll 은 books 컬렉션에 대해서는 my_collections/_books 를, recipes 컬렉션에 대해서는 my_collections/_recipes 를 참고합니다.
# 초안과 포스트를 컬렉션 디렉토리로 옮기세요
# 모든 컬렉션을 한 곳에 보관하려고 collections_dir: my_collections 로 디렉토리를 지정한 후에는, _drafts 와 _posts 디렉토리를 my_collections/_drafts 와 my_collections/_posts 로 옮겨야 합니다.
# 한 가지 기억해야할 것은, 컬렉션을 보관하는 디렉토리 이름은 밑줄(`_`)로 시작할 수 없다는 것입니다.
collections_dir: all_collections
collections:
  posts:
    output: true

# permalink : 생성된 블로그 포스트 URL 을 사이트 전역 스타일(기본설정: /year/month/day/title.html)이 아닌 다른 스타일로 만드려면, 이 변수를 사용하여 최종 URL 을 설정하면 된다.
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]







# # Jekyll configuration
# markdown: kramdown
# # kramdown : markdown의 개조판.
# # markdown에서 불편한 사항을 개선한 형태.

# # MyData
# owner:
#   name:           YoungKwang Kwon
#   avatar:         kwon0koang_profile.jpg
#   bio:            "Android Engineer"
#   email:          kwon0koang@gmail.com
#   # Social networking links used in footer. Update and remove as you like.
#   twitter:
#   facebook:
#   github:
#   stackexchange:
#   linkedin:
#   instagram:
#   flickr:
#   tumblr:
#   # google plus id, include the '+', eg +mmistakes
#   google_plus:

# highlighter: rouge
# # 블로그에 코드가 그냥 들어가면 안이쁨. 하이라이터가 글자색을 바꿔줌
# # text highlighter로 rouge이용
# # 2016.02월 이후로 syntax highlighter는 rouge만 지원.
# # Pygments 사용불가.

# paginate: 20
# # 작성한 모든 post를 하나의 페이지에 열거할 수 없으니
# # pagination이 필요하고 몇개의 post를 하나의 page에서
# # 보여줄 건지를 설정.

# language: 'en-uk'
# # 언어 설정

# url: https://kwon0koang.github.io
# # Google Search Console에서 사용하는 sitemap.xml 생성시
# # 이 url key값이 존재하지 않으면 sitemap.xml이
# # 정상적으로 생성되지 않는다.
# # 또한 disqus(댓글시스템)를 이용하기 위해서도 필요.
# # 자신의 github page url을 입력
# # ( https://your_github_id.github.io 형식 )

# baseurl: /

# # Website info
# title: 권영광 | Android Engineer
# # 자신의 blog title.

# description: 테스트 블로그 홈 표시 설명
# # blog home에 표시될 blog에 대한 전반적인 설명.

# cover: assets/built/images/blog-cover1.png
# # blog home에 표시될 blog cover image.

# logo:
# logo_dark:

# favicon: assets/built/images/favicon.jpg
# # favicon으로 사용할 image

# # production_url: https://kwon0koang.github.io/
# # # 최종적으로 blog가 운영될 url

# # source_url: https://github.com/kwon0koang/GitHubPageMaker/
# # # blogmaker(jekyll source folder)에 대한 github repository

# # Social info
# navigation: True
# # Navigation bar link를 보여줄건지 여부

# subscribers: True
# # subscriber 기능을 사용할건지의 여부
# # 저는 약간의 수정을 통해 subscriber 기능대신
# # lunr.js를 이용한 검색 기능으로 대체 사용했습니다.
# # 검색기능으로 대체하기 위해서
# # `_includes/subscribe-form.html` 파일의 수정이 필요합니다.

# twitter:
# facebook:
# # 만약 twitter와 facebook을 이용하면 username을 입력

# # Disqus
# disqus: True
# disqus_shortname: xxxxxxxx
# # disqus는 온라인 댓글 시스템. 댓글 기능을 사용하기 위해
# # disqus를 이용할 것인지 여부와 만약 사용하면
# # disqus shortname을 입력 ( disqus username이 아님 )


# # Google Analytics
# google_analytics: UA-xxxxxxxx-x # replace with your GA tracking identifier
# # Google Analytics을 사용할 경우 GA tracking identifier를 입력

# # Permalinks
# permalink: /:title
# # permalink: /author/:author
# # permalink: /tag/:title
# # 각각의 post에 고정주소를 어떤 방식으로 할당할 것인지를 결정
# # 이 값을 바꾸면 작성한 포스트의 저장위치나 파일이름이 변경된다.

# # gems and other configs
# plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]

# feed:
#   path: feed.xml

# # Travis-CI 설정입니다.
# safe: False
# lsi: False

# username: kwon0koang
# repo: GitHubPageMaker
# # username : travis-ci와 연동하는 github의 username
# # repo: travis-ci와 연동하는 github의 repository이름
# # https://github.com/<username>/<repository>

# branch: master
# # 사용할 branch명

# relative_source:

# destination: ./output/
# # compile된 결과가 생성되는 폴더
# # 이 폴더안의 내용이 우리가 운영하는 블로그 내용이 컴파일되서 들어간다.
# # 이 폴더안의 내용을 github repository(https://username.github.io)에 push
# # 만약 Travis-CI를 이용할 예정이면 이 부분을 git submodule로
# # github repository(https://username.github.io)에 연결해야 한다.


# # exclude는 Jekyll컴파일 시 destination에 포함될 필요가
# # 없는것들을 명시한다. (node_modules와 필요없는 것들은 제외)
# exclude:
#   - README.md
#   - Rakefile
#   - Gemfile
#   - Gemfile.lock
#   - changelog.md
#   - "*.Rmd"
#   - vendor
#   - .travis.yml
#   - node_modules
#   - assets/css
#   - assets/images
#   - _posts/angular
#   - _posts/et-cetera
#   - _posts/python
#   - _posts/typescript
# #  - _posts/jekyll
#   - _posts/iot
#   - _posts/r
#   - _posts/economy